script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: UCfIhHE6ju3XIwM+gfblSW3pv6MKfeH0YFQrlmAZZRaSmKyGebkqPr4phsA+iphqNuvGBSN5jCFLWzW2obeXHQmfcBQE/F9VauyktBamf86F1UrZ+R+VDmR9yGpeqaWtPwj5ckdeqPArs0gP8yzADCZggCrp+nNYovwO6s+qsxgyfFqcCAz/5cyxxPmjO3WDTZQXcrBfxqV68UbPXx+wKFAbNk0Rea0XcToXApCLIslgkDb9YzgBQulqUcmDCLCdJZAJtvWKQll/LmebTGgT2W6TKe62ZYoRvDBXBNbAPB+G6fGzSJfRiKSt2NEUfTqRWXaqDW+uHH2cIT4c4aCDMVabj7tHCPdB2uaY+KxJHgylo5ysNrPBwx7mNCJCQmgEsBEbSvQNupB/ARqZEeZmvFCpfKoWTXgSrgC5rn24O5v2DPzV30nzpgvp0t6/OEZrIyLDDchYo6zjTKO91zZvmCBmF5ijR13upgPFbrypRN7/3u0DoIL+HoZqwpcKNhLpuWGk/w2COl8UfbyWwmUFymTrsYRsQrcghzxfJZlNsI1QOpCgrfmO77hAB1mF4Iy4rqmYZnsDsEVyy446GWa0mCfx0nYR1QFAMpasiHT5Hu51Q9MFp34Sr5BfEIMtB2qlHeqMr9Etu+ZCtlaqBfps3o9slMZO2LcjiG9ZRVrasAI=
  app: shrouded-lowlands-26799
